### ISSUE TITLE
timing resolution : micro- or nanoseconds ?

### ISSUE THREAD

**Issue by FObersteiner** [hendriknielaender/zBench#10]
according to the [current Timer definition](https://github.com/hendriknielaender/zBench/blob/0dd38e64b1abcaf531e25f6443016f6da770d48a/util/timer.zig#L3), all durations are microseconds. However the [duration formatter](https://github.com/hendriknielaender/zBench/blob/0dd38e64b1abcaf531e25f6443016f6da770d48a/util/format.zig#L3) starts with nanoseconds. Whenever the Timer is stopped, the elapsed duration [gets appended](https://github.com/hendriknielaender/zBench/blob/0dd38e64b1abcaf531e25f6443016f6da770d48a/zbench.zig#L51) and later summed up etc. So if I didn't miss anything, the result should always be microseconds or greater, no ?

zig offers a [nanosecond resolution timestamp](https://github.com/ziglang/zig/blob/master/lib/std/time.zig#L99), as an i128. Did you consider using this?
- assuming no machine that runs your code has its clock set pre-Unix epoch, casting to unsigned should be safe
- according to my datetime calculations, it will overflow in April of the year 2262, so some time to refactor if needed ;-)

Regardless of the used resolution, Zig only seems to give you a CLOCK_REALTIME (see e.g. [clock_gettime](https://man7.org/linux/man-pages/man3/clock_gettime.3.html)), nothing guaranteed to me monotonic. Not sure how go does this for testing, but might be something to keep in mind.

**Comment by FObersteiner** [comment]
I've had a go on this one, see [my fork](https://github.com/hendriknielaender/zBench/compare/main...FObersteiner:zBench:main). I can make a PR if you like.

Concerning #11, I'll leave this up to you how you'd like to handle this :)

**Comment by hendriknielaender** [comment]
Hey @FObersteiner,

appreciate you taking the time to dissect this and even more so, bringing up the Zig's nanosecond timestamp alternative. Missed this detail during development.

Yeah in a previous version i used nanoseconds, but can't remember the reason why i switch to microseconds. So your assumptions are correct 👍 and should be adjusted.

And cool, you’ve already spun this up in a fork? That’s nice! 
Please shoot over a PR when you get a chance.

**Comment by hendriknielaender** [comment]
closed https://github.com/hendriknielaender/zBench/pull/13
