### ISSUE TITLE
calculation of average duration

### ISSUE THREAD

**Issue by FObersteiner** [hendriknielaender/zBench#11]
at the moment, the average execution time is calculated by using [self.totalOperations](https://github.com/hendriknielaender/zBench/blob/0dd38e64b1abcaf531e25f6443016f6da770d48a/zbench.zig#L175) of the Benchmark instance.

If I'm not mistaken, this gives invalid results since the number of ops is incremented in multiple places; [here](https://github.com/hendriknielaender/zBench/blob/0dd38e64b1abcaf531e25f6443016f6da770d48a/zbench.zig#L53) and [here](https://github.com/hendriknielaender/zBench/blob/0dd38e64b1abcaf531e25f6443016f6da770d48a/zbench.zig#L278) - additionally, the user-side code can increment it by calling ` b.incrementOperations(1)`, as in your 'basic' example.

This seems a bit like a separation-of-concerns thing; as a clean solution why not use `self.durations.items.len` as denominator ?

**Comment by hendriknielaender** [comment]
Thank you. You're correct, incrementing `self.totalOperations` in multiple places can lead to inconsistent or incorrect results when calculating the average execution time, especially when `b.incrementOperations(1)` is also called in the user-side code.

I've created a Pull Request to implement this change. Feel free to review and provide any feedback.
