### ISSUE TITLE
Add Memory Consumption Calculation to Benchmark Function

### ISSUE THREAD

**Issue by hendriknielaender** [hendriknielaender/zBench#4]
## 🚀 Feature Proposal

Enhance the benchmark function to also measure and display memory consumption for the functions/methods being benchmarked?

## Motivation

- **Performance Insight**: While execution time gives us a good measure of efficiency, understanding memory consumption can be just as crucial, especially for applications running in memory-constrained environments or when dealing with large datasets.
  
- **Developer Awareness**: Memory metrics will empower developers to make informed decisions about trade-offs, potentially leading to more optimized solutions.
  
- **Holistic Analysis**: Providing both time and space performance metrics offers a more rounded view of our functions' efficiency.

## Proposed Implementation

1. Explore Zig's built-in functionalities for memory profiling.
2. Integrate the memory measurement step within the existing benchmarking process.
3. Present the memory consumption metrics alongside the current execution time metrics in the benchmark results.

## Additional Context

- **Accuracy is Key**: It's imperative that the memory measurements are accurate and that the measuring process itself doesn't introduce significant overhead or bias.
  
- **Toggle Feature**: Ideally, we should have the ability to toggle this feature on and off based on our benchmarking requirements.
  
- **Documentation**: Once implemented, a brief section in our project's documentation explaining how to interpret these memory metrics would be beneficial.

**Comment by FObersteiner** [comment]
I think this would be very helpful. Since Zig puts emphasis on manual memory management, I would be very much interested how my changes to the code affect memory consumption.

**Comment by jasperdunn** [comment]
Yeah, this would be incredible 🚀
