### ISSUE TITLE
Non-ASCII characters not printed correctly on Windows

### ISSUE THREAD

**Issue by FObersteiner** [hendriknielaender/zBench#48]
https://github.com/hendriknielaender/zBench/blob/f88d20b21748881240d8b34078684bfe3f2cc5b7/util/format.zig#L28

Windows uses UTF-16 LE by default, not UTF-8, so characters like "plusminus" or "sigma" might get messed up

**Comment by FObersteiner** [comment]
related : https://github.com/ziglang/zig/issues/7600

**Comment by hendriknielaender** [comment]
Added it to the readme. 👍 
https://github.com/hendriknielaender/zBench/pull/50

**Comment by FObersteiner** [comment]
related: https://github.com/ziglang/zig/issues/18229 - might [this](https://github.com/ziglang/zig/issues/18229#issuecomment-2504653774) help so that users do not have to modify Windows settings?
