### ISSUE TITLE
Migrate to Zig 0.13

### ISSUE THREAD

**Issue by FObersteiner** [hendriknielaender/zBench#84]
Zig 0.13 got released: https://ziglang.org/download/0.13.0/release-notes.html

Most severe change is the `std.Progress` API; [new](https://github.com/ziglang/zig/blob/master/lib/std/Progress.zig) vs. [old](https://github.com/ziglang/zig/blob/0.12.x/lib/std/Progress.zig).

**Comment by ivanstepanovftw** [comment]
Also migration guide:

```zig
exe.addAnonymousModule("zbench", .{
  .source_file = .{ .path = "libs/zbench/zbench.zig" },
});
```
V
```zig
exe.root_module.addAnonymousImport("zbench", .{
  .root_source_file = b.path("libs/zbench/zbench.zig"),
});
```
