### ISSUE TITLE
No output when running zig build examples

### ISSUE THREAD

**Issue by finlaydotb** [hendriknielaender/zBench#93]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

When I run `zig build examples` I don't see any output. The project builds but it does not show any output showing result of the benchamark.

### Expected Behavior

The output to show results of benchmark.

**Comment by FObersteiner** [comment]
> The project builds

could you please clarify, did you try to *run* one of the examples from `/zig-out/bin` ?

**Comment by FObersteiner** [comment]
Seems the readme is misleading here... the `examples` step just *builds* the examples to `./zig-out/bin` by default, it doesn't *run* them.
